apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-app-discovery
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: observability
roleRef:
  kind: ClusterRole
  name: prometheus-app-discovery
  apiGroup: rbac.authorization.k8s.io

